version: '3'
services:
  kalki-iot-interface:
    build: .
    image: kalki/kalki-iot-interface
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    ports:
      - 5050:5050
    depends_on:
      - kalki-iot-wemo
    command: ${CMD_PARAMS}
  kalki-iot-wemo:
    build: plugins/WeMoInsight/api/
    image: kalki/kalki-iot-wemo
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    ports:
      - 7501:7501
